version: "3.0"

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    environment:
      - HOST_NAME=${HOST_NAME}
      - HOST_IPV4=${HOST_IPV4}
      - HOST_IPV6=${HOST_IPV6}
      - MARIADB_DB=${MARIADB_DB}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
      - MARIADB_ADMIN_USER=${MARIADB_ADMIN_USER}
      - MARIADB_ADMIN_PWD=${MARIADB_ADMIN_PWD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ADMIN_PWD}
    image: mariadb
    networks:
      - network-mariadb
    restart: always
    volumes:
      - volume-mariadb:/var/lib/mysql
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    networks:
      - network-nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - volume-wordpress:/var/www/wordpress
  redis:
    build: ./requirements/bonus/redis/
    container_name: redis
    image: redis
    networks:
      - network-redis
    restart: always
  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    environment:
      - WP_URL=${WP_URL}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PWD=${WP_USER_PWD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
      - MARIADB_DB=${MARIADB_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CON_TIMEOUT=${REDIS_CON_TIMEOUT}
      - REDIS_READ_TIMEOUT=${REDIS_READ_TIMEOUT}
      - REDIS_DB_INDEX=${REDIS_DB_INDEX}
    image: wordpress
    depends_on:
      - mariadb
    networks:
      - network-mariadb
      - network-nginx
      - network-redis
    restart: always
    volumes:
      - volume-wordpress:/var/www/wordpress
  vsftpd:
    build: ./requirements/bonus/vsftpd/
    container_name: vsftpd
    environment:
      - FTP_ROOT_DIR=${FTP_ROOT_DIR}
      - FTP_USER=${FTP_USER}
      - FTP_PWD=${FTP_PWD}
    image: vsftpd
    restart: always
    ports:
      - "21:21"
    volumes:
      - volume-wordpress:/var/www/wordpress
  grafana:
    build: ./requirements/bonus/grafana/
    container_name: grafana
    image: grafana
    networks:
      - network-nginx
      - network-monitor
    restart: always
    volumes:
      - volume-monitor:/monitor
  cadvisor:
    build: ./requirements/bonus/cadvisor/
    container_name: cadvisor
    environment:
      - CADVISOR_PORT=${CADVISOR_PORT}
      - CADVISOR_URL_BASE_PREFIX=${CADVISOR_URL_BASE_PREFIX}
    image: cadvisor
    networks:
      - network-monitor
    privileged: true
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
networks:
  network-mariadb:
    driver: bridge
    name: network-mariadb
  network-nginx:
    driver: bridge
    name: network-nginx
  network-redis:
    driver: bridge
    name: network-redis
  network-vsftpd:
    driver: bridge
    name: network-vsftpd
  network-monitor:
    driver: bridge
    name: network-monitor
volumes:
  volume-mariadb:
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/mariadb
      o: bind
      type: volume
    name: volume-mariadb
  volume-wordpress:
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/wordpress
      o: bind
      type: volume
    name: volume-wordpress
  volume-site:
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/site
      o: bind
      type: volume
    name: volume-site
  volume-monitor:
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/monitor
      o: bind
      type: volume
    name: volume-monitor
